services:
  servidor:
    build:
      context: .
      dockerfile: docker\servidor\sv.dockerfile
    ports:
      - "8080:8080"

  cliente:
      build:
        context: .
        dockerfile: docker/cliente/c.dockerfile
      depends_on:
        - servidor
      tty: true
      stdin_open: true
  
  sensor1:
    build:
      context: .
      dockerfile: docker\sensor/sensor1/ss1.dockerfile

  sensor2:
    build:
      context: .
      dockerfile: docker\sensor/sensor2/ss2.dockerfile
  atuador1:
    build:
      context: .
      dockerfile: docker\atuador/atuador1/a1.dockerfile