services:
  servidor:
    build:
      context: .
      dockerfile: sv.dockerfile
    ports:
      - "8080:8080/udp"
    environment:
      # O servidor precisa saber onde estão o Cliente e o Atuador na rede física
      - CLIENTE_ADDR=192.168.15.71

      - ATUADOR_ADDR=192.168.15.71