services:
  servidor:
    build:
      context: .
      dockerfile: sv.dockerfile
    ports:
      - "8080:8080/udp"  # Escuta o Sensor na rede física
      - "8081:8080/tcp"  # <-- Escuta os comandos TCP do Cliente
    environment:
      - CLIENTE_ADDR=192.168.0.118:8080
      - ATUADOR_ADDR=192.168.0.118:8080