services:
  cliente:
    build:
      context: .
      dockerfile: c.dockerfile
    environment:
      # O cliente precisa saber qual é o IP físico da máquina do Servidor
      - SERVIDOR_ADDR=192.168.15.71
